public class Houston {
	// 8 tuples per block
	 String customer_table[][]={
			  {"customer-name","customer-street","customer-city"},
			  {"Van Rodriquez",	"100th Cir",	"Omaha"},
			  {"Charlene Nash",	"100th Cir",	"Omaha"},
			  {"Doreen Gardner",	"100th Plaza",	"Omaha"},
			  {"Tracey Oliver",	"101st Plaza",	"Omaha"},
			  {"Edwin Hughes",	"104th Ave",	"Omaha"},
			  {"Madeline Estrada",	"106th St",	"Omaha"},
			  {"Jaime Kelley",	"107th St",	"Omaha"},
			  {"Tiffany Reyes",	"109th Ct",	"Omaha"},
			  {"Harry Reed",	"Franklin Ave",	"New York"},
			  {"Pauline Gordon",	"Lawrence St",	"New York"},
			  {"Debra Soto",	"Orange St",	"New York"},
			  {"Ramona Moran",	"Richmond St",	"New York"},
			  {"Saul Parker",	"S Myrtle Ave",	"New York"},
			  {"Carol Diaz",	"100th St",	"New York"},
			  {"Sheila Long", "101st Ave"	,"New York"},
			  {"Molly Bowen",	"101st St",	"New York"},
			  {"Dorothy Smith",	"10th Ave",	"New York"},
			  {"Jeanette Ball",	"101 St",	"Houston"},
			  {"Silvia Stanley",	"103 St",	"Houston"},
			  {"Shawna Powers",	"104 St",	"Houston"},
			  {"Rafael Mcgee",	"105 St",	"Houston"},
			  {"Diana Meyer",	"10th St",	"Houston"},
			  {"Billie Crawford",	"11th",	"Houston"},
			  {"Wayne Tate",	"11th St",	"Houston"},
          {"Felix Clayton",	"12 Oaks Dr",	"Houston"},
			  {"Lynda Richards",	"12th St",	"Houston"},
			  {"Anthony Coleman",	"1959 Rd",	"Houston"},
			  {"Brendan Sullivan",	"1st St",	"Houston"},
			  {"Stacey Goodman",	"2 Oaks Cir",	"Houston"},
			  {"Milton Pope",	"2218 Rd",	"Houston"},
			  {"Rosemary Morton", "22nd St",	"Houston"},
			  {"Latoya Moreno",	"290 Hov Fwy",	"Houston"}, 
			  {"Omar Tyler",	"290 Hov Fwy",   "Houston"},
			  {"Rhonda Jensen",	"2nd St",	"Houston"},
			  {"Pete Graham",	"10th Ave",	"San Francisco"},
			  {"Elias Garrett",	"10th St",	"San Francisco"},
			  {"Angel Mathis",	"11th Ave",	"San Francisco"},
			  {"Amos Weaver",	"11th St",	"San Francisco"},
			  {"Irving Lowe",	"12th Ave",	"San Francisco"},
			  {"Woodrow Wallace",	"12th St",	"San Francisco"},
		      {"Margaret Burke",	"13th St",	"San Francisco"},
			  {"Lionel Lawson",	"14th Ave",	"San Francisco"},
			  {"Kristopher Poole",	"14th St",	"San Francisco"},
			  {"Israel Mullins",	"15th Ave",	"San Francisco"},
			  {"Rolando Harrington",	"15th St",	"San Francisco"},
			  {"Neil French", "16th Ave",	"San Francisco"},
			  {"Gilbert Hamilton","16th St",	"San Francisco"},
			  {"Blanca Saunders","17th Ave",	"San Francisco"},
      	  {"Elena Mcdonald",	"17th St",	"San Francisco"},
			  {"Brent Lamb",	"18th Ave",	"San Francisco"},
			  {"Alton Day",	"18th St",	"San Francisco"},
			  {"Courtney Ingram",	"Bay 10th St",	"New York"},
			  {"Kay Russell",	"Bay 11th St",	"New York"},
			  {"Brandy Casey",	"Bay 13th St",	"New York"},
			  {"Dan Dennis",	"Bay 14th St",	"New York"},
			  {"Pablo Baker",	"Bay 16th St",	"New York"},
			  {"Stuart Hunter",	"Bay 17th St",	"New York"},
			  {"Bessie Wilkins",	"Bay 19th St",	"New York"},
			  {"Irma Gutierrez",	"Bay 20th St",	"New York"},
			  {"Earnest James",	"Bay 22nd St",	"New York"},

};

}
